permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

name : Science Dataist
title : Science Dataist
description: Ken Cavagnolo's data science tinkering and thoughts.
author :
  name : Ken Cavagnolo
  email : ken@kcavagnolo.com
  github : kcavagnolo
  twitter : KenCavagnolo
  linkedin : kencavagnolo

url : http://www.kcavagnolo.com/blog
production_url : http://www.kcavagnolo.com/blog

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-gist

JB :
  version : 1.0.0
  BASE_PATH : http://www.kcavagnolo.com/blog
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments :
    provider :
    disqus :
      short_name :
    livefyre :
      site_id : 
    intensedebate :
      account : 
    facebook :
      appid : 
      num_posts: 
      width: 580
      colorscheme: light
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-8034516-4'
    getclicky :
      site_id : 
    mixpanel :
        token : 
    piwik :
        baseURL : 
        idsite : 
  sharing :
    provider : twitter
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
